Repository SciSharp/LLamaSharp, pull requests merged in 2023-11, with the labels that each got.

#226 Adapts to SK Kernel Memory
  LLama.Examples/Assets/sample-SK-Readme.pdf
  LLama.Examples/LLama.Examples.csproj
  LLama.Examples/NewVersion/KernelMemory.cs
  LLama.Examples/NewVersion/TestRunner.cs
  LLama.KernelMemory/BuilderExtensions.cs
  LLama.KernelMemory/LLamaSharp.KernelMemory.csproj
  LLama.KernelMemory/LLamaSharpTextEmbeddingGeneration.cs
  LLama.KernelMemory/LlamaSharpConfig.cs
  LLama.KernelMemory/LlamaSharpTextGeneration.cs
  LLamaSharp.sln
Labels: enhancement

#274 Update ToLLamaSharpChatHistory extension method to be public and support semantic-kernel author roles
  LLama.SemanticKernel/ExtensionMethods.cs
Labels: enhancement

#258 Runtime detection MacOS
  .github/prepare_release.sh
  .github/workflows/compile.yml
  .github/workflows/main.yml
  LLama.Examples/NewVersion/GetEmbeddings.cs
  LLama.Examples/NewVersion/QuantizeModel.cs
  LLama.Examples/NewVersion/TestRunner.cs
  LLama.Web/Common/ModelOptions.cs
  LLama/Abstractions/IContextParams.cs
  LLama/Common/FixedSizeQueue.cs
  LLama/Common/ModelParams.cs
  LLama/Extensions/DictionaryExtensions.cs
  LLama/Extensions/EncodingExtensions.cs
  LLama/Extensions/IContextParamsExtensions.cs
  LLama/Extensions/IEnumerableExtensions.cs
  LLama/Extensions/KeyValuePairExtensions.cs
  LLama/Extensions/ListExtensions.cs
  LLama/LLamaSharp.Runtime.targets
  LLama/Native/LLamaContextParams.cs
  LLama/Native/NativeApi.cs
  LLama/runtimes/build/LLamaSharp.Backend.Cpu.nuspec
  LLama/runtimes/build/LLamaSharp.Backend.MacMetal.nuspec
  LLama/runtimes/build/LLamaSharpBackend.props
  LLama/runtimes/osx-arm64/ggml-metal.metal
  LLama/runtimes/osx-arm64/libllama.dylib
  LLama/runtimes/osx-x64/libllama.dylib
  README.md
Labels: enhancement, distribution, break change

#275 feat: cuda feature detection.
  .github/prepare_release.sh
  .github/workflows/release-minor.yml
  .github/workflows/release-patch.yml
  LLama.Examples/Program.cs
  LLama.KernelMemory/LLamaSharp.KernelMemory.csproj
  LLama.SemanticKernel/LLamaSharp.SemanticKernel.csproj
  LLama/AntipromptProcessor.cs
  LLama/LLamaSharp.Runtime.targets
  LLama/LLamaSharp.csproj
  LLama/Native/NativeApi.Load.cs
  LLama/Native/NativeApi.cs
  LLama/Native/NativeLibraryConfig.cs
  LLama/StreamingTokenDecoder.cs
  LLama/runtimes/build/LLamaSharp.Backend.Cuda11.nuspec
  LLama/runtimes/build/LLamaSharp.Backend.Cuda12.nuspec
  LLama/runtimes/build/LLamaSharpBackend.props
  README.md
Labels: enhancement, minor-release, distribution

#326 fix: Chinese encoding error with gb2312.
  LLama.Examples/Assets/chat-with-kunkun-chinese.txt
  LLama.Examples/Examples/ChatChineseGB2312.cs
  LLama.Examples/Examples/Runner.cs
  LLama.Examples/LLama.Examples.csproj
  LLama/Native/NativeApi.cs
Labels: bug

#334 ci: fix error in auto-release.
  .github/prepare_release.sh
Labels: bug
