Repository SciSharp/LLamaSharp, pull requests merged in 2024-06, with the labels that each got.

#778 Add OAI demo link
  README.md
Labels: documentation

#777 StreamingTextDecoder Special Token Support
  LLama/StreamingTokenDecoder.cs
Labels: enhancement

#755 Add Rosetta2 Binaries
  .github/workflows/compile.yml
  LLama/LLamaSharp.Runtime.targets
  LLama/Native/Load/NativeLibraryWithMacOrFallback.cs
  LLama/runtimes/build/LLamaSharp.Backend.Cpu.nuspec
Labels: enhancement, backend, native lib

#779 v0.13.0 release
  README.md
Labels: minor-release

#780 ci: fix auto-release error.
  LLama.Experimental/LLama.Experimental.csproj
  LLama/LLamaSharp.csproj
Labels: minor-release, ci/cd

#781 ci: update nuget key info.
  .github/workflows/release-minor.yml
  .github/workflows/release-patch.yml
Labels: minor-release, ci/cd
