Repository SciSharp/LLamaSharp, pull requests merged in 2024-04, with the labels that each got.

#642 fix: llava backend ignores avx and cuda.
  .github/workflows/compile.yml
  LLama/runtimes/build/LLamaSharp.Backend.Cpu.nuspec
  LLama/runtimes/build/LLamaSharp.Backend.Cuda11.nuspec
  LLama/runtimes/build/LLamaSharp.Backend.Cuda12.nuspec
  LLama/runtimes/build/LLamaSharp.Backend.OpenCL.nuspec
Labels: llava, backend

#651 [Release] v0.11.2
  LLama.KernelMemory/LLamaSharp.KernelMemory.csproj
  LLama.SemanticKernel/LLamaSharp.SemanticKernel.csproj
  LLama/LLamaSharp.csproj
  README.md
Labels: patch-release, distribution

#708 Add LLaMA3 chat session example.
  LLama.Examples/ExampleRunner.cs
  LLama.Examples/Examples/LLama3ChatSession.cs
  LLama/LLamaTransforms.cs
Labels: bug

#710 ci: add workflow to check the spellings.
  .github/_typos.toml
  .github/workflows/spell_check.yml
  LLama.Examples/Examples/BatchedExecutorSaveAndLoad.cs
  LLama.Examples/Examples/LlavaInteractiveModeExecute.cs
  LLama.Examples/Examples/SpeechChat.cs
  LLama.Web/Async/AsyncLock.cs
  LLama.Web/Extensions.cs
  LLama.Web/Hubs/SessionConnectionHub.cs
  LLama.Web/README.md
  LLama.Web/Services/ModelService.cs
  LLama/Abstractions/IInferenceParams.cs
  LLama/Abstractions/ILLamaExecutor.cs
  LLama/Abstractions/IModelParams.cs
  LLama/ChatSession.cs
  LLama/Common/InferenceParams.cs
  LLama/Extensions/IContextParamsExtensions.cs
  LLama/Extensions/IModelParamsExtensions.cs
  LLama/LLamaContext.cs
  LLama/LLamaExecutorBase.cs
  LLama/LLamaInstructExecutor.cs
  LLama/LLamaInteractExecutor.cs
  LLama/LLamaStatelessExecutor.cs
  LLama/Native/NativeApi.LLava.cs
  LLama/Native/NativeApi.Load.cs
  LLama/Native/NativeLibraryConfig.cs
  README.md
  docs/Examples/LLavaInteractiveModeExecute.md
  docs/FAQ.md
  docs/QuickStart.md
  docs/Tutorials/Executors.md
  docs/Tutorials/NativeLibraryConfig.md
  docs/index.md
  docs/xmldocs/llama.abstractions.iinferenceparams.md
  docs/xmldocs/llama.common.inferenceparams.md
Labels: ci/cd

#709 ci: add a workflow to check code format.
  .editorconfig
  .github/workflows/code_format.yml
Labels: ci/cd

#671 Optimize Semantic Kernel LLamaSharpChatCompletion when running with StatefulExecutorBase models
  LLama.SemanticKernel/ChatCompletion/LLamaSharpChatCompletion.cs
Labels: enhancement
