Repository SciSharp/LLamaSharp, pull requests merged in 2024-05, with the labels that each got.

#723 ci: add windows benchmark test.
  .github/workflows/benchmark.yml
  LLama.Benchmark/LLamaExecutorBenchmark/Prefill.cs
Labels: ci/cd, benchmark

#728 Improved Example Docs
  docs/Examples/BatchedExecutorFork.md
  docs/Examples/BatchedExecutorGuidance.md
  docs/Examples/BatchedExecutorRewind.md
Labels: documentation

#688 feat: optimize the native library loading.
  LLama.Examples/Program.cs
  LLama/Abstractions/INativeLibrary.cs
  LLama/Abstractions/INativeLibrarySelectingPolicy.cs
  LLama/LLamaSharp.csproj
  LLama/Native/Load/DefaultNativeLibrarySelectingPolicy.cs
  LLama/Native/Load/NativeLibraryConfig.cs
  LLama/Native/Load/NativeLibraryFromPath.cs
  LLama/Native/Load/NativeLibraryMetadata.cs
  LLama/Native/Load/NativeLibraryUtils.cs
  LLama/Native/Load/NativeLibraryWithAvx.cs
  LLama/Native/Load/NativeLibraryWithCuda.cs
  LLama/Native/Load/NativeLibraryWithMacOrFallback.cs
  LLama/Native/Load/SystemInfo.cs
  LLama/Native/Load/UnknownNativeLibrary.cs
  LLama/Native/NativeApi.Load.cs
  LLama/Native/NativeApi.cs
  LLama/Native/NativeLibraryConfig.cs
  LLama/Native/NativeLogConfig.cs
Labels: enhancement, native lib

#747 docs: add documentation for the change of native library loading.
  docs/AdvancedTutorials/CustomizeNativeLibraryLoading.md
  docs/Tutorials/NativeLibraryConfig.md
  mkdocs.yml
Labels: documentation

#767 ci: remove the duplicated file copy.
  .github/workflows/compile.yml
Labels: ci/cd
