Repository SciSharp/LLamaSharp, pull requests merged in 2024-03, with the labels that each got.

#587 update readme.md backends
  README.md
Labels: documentation

#563 Llava api
  .github/workflows/compile.yml
  .github/workflows/main.yml
  LLama.Unittest/Constants.cs
  LLama.Unittest/LLama.Unittest.csproj
  LLama.Unittest/LLamaEmbedderTests.cs
  LLama.Unittest/LLavaWeightsTests.cs
  LLama.Unittest/Models/extreme-ironing-taxi-610x427.jpg
  LLama/LLamaSharp.Runtime.targets
  LLama/LLavaWeights.cs
  LLama/Native/LLavaImageEmbed.cs
  LLama/Native/NativeApi.LLava.cs
  LLama/Native/NativeApi.Load.cs
  LLama/Native/SafeLlavaImageEmbedHandle.cs
  LLama/Native/SafeLlavaModelHandle.cs
Labels: enhancement, break change, llava

#603 `SetDllImportResolver` based loading
  LLama.Examples/Program.cs
  LLama/Native/NativeApi.Load.cs
  LLama/Native/NativeLibraryConfig.cs
Labels: enhancement, backend

#560 Chat session state management
  LLama.Examples/ExampleRunner.cs
  LLama.Examples/Examples/ChatSessionWithHistory.cs
  LLama.Examples/Examples/ChatSessionWithRestart.cs
  LLama/Abstractions/IHistoryTransform.cs
  LLama/Abstractions/ITextStreamTransform.cs
  LLama/Abstractions/ITextTransform.cs
  LLama/ChatSession.cs
  LLama/Common/ChatHistory.cs
  LLama/Common/PolymorphicJSONConverter.cs
  LLama/LLamaContext.cs
  LLama/LLamaExecutorBase.cs
  LLama/LLamaInstructExecutor.cs
  LLama/LLamaInteractExecutor.cs
  LLama/LLamaTransforms.cs
Labels: enhancement, break change

#615 [LLama.KernelMemory] Fixed System.ArgumentException: EmbeddingMode must be true & #617
  LLama.KernelMemory/BuilderExtensions.cs
  LLama.KernelMemory/LLamaSharpTextEmbeddingGenerator.cs
  LLama.KernelMemory/LlamaSharpConfig.cs
  LLama.KernelMemory/LlamaSharpTextGenerator.cs
Labels: bug

#630 KernelMemory update with adding the use of already loaded model
  LLama.KernelMemory/BuilderExtensions.cs
Labels: enhancement

#609 Feature: Llava executor
  .github/workflows/compile.yml
  LLama.Examples/ExampleRunner.cs
  LLama.Examples/Examples/LlavaInteractiveModeExecute.cs
  LLama.Examples/Examples/StatelessModeExecute.cs
  LLama.Examples/LLama.Examples.csproj
  LLama.Examples/UserSettings.cs
  LLama.Unittest/LLavaWeightsTests.cs
  LLama/Abstractions/ILLamaExecutor.cs
  LLama/LLamaExecutorBase.cs
  LLama/LLamaInteractExecutor.cs
  LLama/LLamaStatelessExecutor.cs
  LLama/LLavaWeights.cs
  LLama/Native/NativeApi.LLava.cs
  LLama/Native/SafeLlavaImageEmbedHandle.cs
  LLama/Native/SafeLlavaModelHandle.cs
Labels: enhancement, break change, llava

#631 Add path to find llama.dll for MAUI
  LLama/Native/NativeApi.Load.cs
  LLama/Native/NativeApi.cs
Labels: bug

#633 fix: the missing of llava_shared library.
  LLama/runtimes/build/LLamaSharp.Backend.Cpu.nuspec
  LLama/runtimes/build/LLamaSharp.Backend.Cuda11.nuspec
  LLama/runtimes/build/LLamaSharp.Backend.Cuda12.nuspec
  LLama/runtimes/build/LLamaSharp.Backend.OpenCL.nuspec
  docs/css/extra.css
  docs/media/icon128.png
  mkdocs.yml
Labels: documentation, patch-release, distribution
